import Head from 'next/head'
import Image from 'next/image'


function Posters() {
    return (
        <>
            <Head>
                <title>Mughal Print Store - Posters</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="b-gray-100 overflow-y-hidden">
                <div className="w-full flex flex-wrap">
                    <div className="relative rounded-lg w-full bg-gray-100 mx-auto lg:flex md:flex-wrap items-center pt-12 sm:pt-24 pb-12 lg:pb-24">
                        <div className="w-full lg:w-3/6">
                            <p className="text-3xl text-center text-red-500">Lijntekeningen</p>

                            <div className="">
                            
                                
                            </div>


                        </div>

                        <div className="w-full lg:w-3/6">
                            <p className="text-3xl text-center text-red-500">Budget posters</p>

                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}

export default Posters;
